### ISSUE TITLE
[PoE2] - Unique price-checking

### ISSUE THREAD

**Issue by Stally18** [Kvan7/Exiled-Exchange-2#180]
**Describe the problem**
When price-checking a unique item, you get its flavour text instead of its stats.
Having unique's stats to filter out is more important now in POE2 since corrupted ones can have their values above or below regular range and be worth way more.

**To Reproduce**
1. Try to price-check any unique
2. See its flavour text strings as a 'Not recognized modifier'

**Expected behavior**
Its actual stats with the min/max boxes.
Stats indeed available with the 'hidden' switch, but this feels wrong.

**Screenshots**
![изображение](https://github.com/user-attachments/assets/02e281cc-54d0-44b0-9665-e00d6c85118f)

**Comment by Kvan7** [comment]
Yep, I just haven't gotten to uniques yet. tbh it just wasn't my priority since _usually_ they are just 1ex max. This was a good note since I hadn't updated my working (#1) and not working (#2) features list in a while. They have now been updated and I'll link them in the pinned issue. 

On a more specific note to Uniques, I still haven't looked at them yet. I'm going to leave this issue open as the top level one for uniques but more granular tracking can be found under [milestone #4](https://github.com/Kvan7/Exiled-Exchange-2/milestone/4)
