### ISSUE TITLE
[Not Recognized Modifier] - Missing Stats

### ISSUE THREAD

**Issue by HarveyK1** [Kvan7/Exiled-Exchange-2#182]
## Not Recognized Modifier
***Put name of item here, and in the title***
`Text of the modifier here`

### Item Text
***Please provide the item's description***
- Can be copied with `ctrl`+`shift`+`c`
- Can also be copied from below the error message
![image](https://github.com/user-attachments/assets/5aa20f11-0b4c-4408-aa80-efd3b3b4b035)

Added phys, cold & lightning damage missing. And will there be a dps meter box for wands? 

And about the removal of the currency exchange of poe1 items in the top left is there a way to do it with poe2 currency? I know a website that tracks items and prices for poe2 like poe.ninja does for poe1.

Merry christmas :)

**Comment by Kvan7** [comment]
> Added phys, cold & lightning damage missing

These are automatically added in as the `dps`. you should be able to see only phys or only ele if you show hidden mods. The actual stats aren't shown since in 99.9% of cases a person searching to buy an item doesn't actually care if the item has the exact mod `adds 9 to 10 phys damage` they just care about the dps, so adding those mods makes the query a lot more limiting in terms of what shows up and can seem to inflate the value of a very common item, (similar to if you just check all the boxes everything is worth like 30 div)

> And will there be a dps meter box for wands?

It should show up? idk I honestly haven't tested it on wands. I would need to check awakened to see if that is intended. I don't play magic (  https://github.com/Kvan7/Exiled-Exchange-2/issues/62#issuecomment-2543357635 ). As far as I know, I have heard the weapon itself doesn't matter as much for magic compared to melee or bows.

> exchange rates

I know of a few websites, I'm planning to reach out myself to them in a week or two once they are more established. After that I'm going to try and work on a solution so their sites don't just get slammed(probably some cloudflare cache stuff). But I want them to not have to worry about having so many users on just their api until they are more set up.

**Comment by HarveyK1** [comment]
Ah okay that makes sense was just curious as if it was intended that the stats weren't there. Yea the dps for wands doesn't show up I'm not sure if it's intended like that as I don't play magic either so I wouldn't know. Makes sense, I've been using a few other websites and it would be cool to see the exchange rates tab be implemented again.

Loving the updates and how it is turning out for poe2 exile exchange 👍
