### ISSUE TITLE
All my stuff

### ISSUE THREAD

**Issue by meoweasy** [Kvan7/Exiled-Exchange-2#65]
Hello, i don`t know why but all my items " If this Item was introduced in this League, it will likely be supported in the next app update". Pls help

**Comment by Kvan7** [comment]
What version are you running? you can see this in the `about` tab

**Comment by meoweasy** [comment]
0.1.0

**Comment by Kvan7** [comment]
Alright, that is the latest. can you paste a screenshot of a item + the overlay? and/or copy the item text into a comment, you can copy the text by just `ctrl+c` while hovering over an item

**Comment by meoweasy** [comment]
![21](https://github.com/user-attachments/assets/ed0f6415-64fa-479f-8d0d-f06f47cdd38c)
![Value](https://github.com/user-attachments/assets/f7712980-aa23-42b8-bfea-26f7cf2719ef)

**Comment by meoweasy** [comment]
Even changing the language to English shows the same thing

**Comment by Kvan7** [comment]
Yes, it is due to the language being Russian. At this moment I only have updated the items/stats for English, since I have honestly just been rushing to get a working version out. I'm not going to commit to get other languages working yet, just since there are many other problems still at the moment. In theory it _shouldn't_ be that difficult since SnosMe put a lot of work into making localization support.

**Comment by Kvan7** [comment]
> Even changing the language to English shows the same thing

Looks like you may have not switched the overlay to use english as well

**Comment by meoweasy** [comment]
Everything worked, thanks
