### ISSUE TITLE
Leagues aren't loading

### ISSUE THREAD

**Issue by Elledar** [Kvan7/Exiled-Exchange-2#8]
![image](https://github.com/user-attachments/assets/7eb93a76-8565-45b5-bc12-0a15cc076413)
Hi! Something wrong...

**Comment by DanSnakee** [comment]
I've same problem
![изображение_2024-12-10_234453515](https://github.com/user-attachments/assets/e43662c8-aec4-4992-9fd5-215c9764fed1)
![изображение_2024-12-10_234523470](https://github.com/user-attachments/assets/1ab99534-a116-4898-aad9-c04cdea306ee)
![Uploading изображение_2024-12-10_234545383.png…]()

**Comment by Kvan7** [comment]
This is two separate issues, 
- Leagues not loading
- Items not found

Items not found will take some time, see currently not working features. This is similar to a new league and having to wait for the update, but this will take longer since it's the whole game

Leagues not working I will investigate further tonight

**Comment by Runo231** [comment]
I have same issue

**Comment by RelaxTDM** [comment]
so, how to fix that, I download the setup [Awakened-PoE2-Trade2-Setup-0.0.1.exe]. Open, try to price check any item and have same problem. We need guide to what we need to do

**Comment by Kvan7** [comment]
Fixed in latest release
